server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'user'
    url: jdbc:postgresql://localhost:54320/fraud
    password: 'admin'

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        hbm2ddl:
          auto: update
        show_sql: 'true'
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true